kursovay1/kursovay1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

kursovay1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.main, name='main'),
    path('invoices/', views.invoices, name='invoices'),
    path('report/', views.report, name='report'),
    path('workspace/', views.workspace, name='workspace'),
    path('order_sup', views.order_sup, name='order_sup'),
    path('create_order_sup/', views.create_order_sup, name='create_order_sup'),
    path('form_order_sup/<int:order_id>', views.form_order_sup, name='form_order_sup'),
    path('logout/', views.logout_user, name='logout'),
    path('order_cust/', views.order_cust, name='order_cust'),
    path('order_cust_type/<int:order_id>', views.order_cust_type, name='order_cust_type'),
    path('create_order_cust_detail/<int:order_id>', views.create_order_cust_detail, name='create_order_cust_detail'),
    path('invoice_detail/<int:order_id>', views.invoice_detail, name='invoice_detail'),
    path('add_invoice_detail/<int:order_id>/<int:item_id>', views.add_invoice_detail, name='add_invoice_detail'),
    path('func/', views.ChartData.as_view(), name='func'),
    path('form_order_cust/<int:order_id>', views.form_order_cust, name='form_order_cust'),
    path('create_order_cust/', views.create_order_cust, name='create_order_cust'),
]

kursovay1/main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.


class OrderCust(models.Model):
    date = models.DateTimeField(default=datetime.now())
    customer = models.ForeignKey(to=User, on_delete=models.CASCADE, default=None)
    customer_name = models.CharField(max_length=100)
    customer_phone = models.CharField(max_length=20)
    car = models.CharField(max_length=100)
    prepayment = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_time = models.DateTimeField()
    type_sale = models.CharField(default='Наличный расчёт', max_length=100)

    def __str__(self):
        return f"Заказ для {self.customer_name}"


class SparePart(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return self.name


class OrderCustItem(models.Model):
    order = models.ForeignKey(OrderCust, on_delete=models.CASCADE, related_name='items')
    spare_part = models.ForeignKey(SparePart, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity} x {self.spare_part.name}"


class OrderSup(models.Model):
    date = models.DateTimeField(default=datetime.now())
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)

    def __str__(self):
        return f"Заказ для {self.supplier}"


class OrderSupItem(models.Model):
    order = models.ForeignKey(OrderSup, on_delete=models.CASCADE, related_name='items')
    spare_part = models.ForeignKey(SparePart, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.quantity} x {self.spare_part.name}"


class Invoice(models.Model):
    date = models.DateTimeField(default=datetime.now())
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)

    def __str__(self):
        return f"Накладная для {self.supplier}"


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
    spare_part = models.ForeignKey(SparePart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sum_of = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity} x {self.spare_part.name}"

kursovay1/main/forms.py
from django import forms
from .models import OrderCust, OrderCustItem, Invoice, InvoiceItem, OrderSup


class OrderCustForm(forms.ModelForm):
    class Meta:
        model = OrderCust
        fields = '__all__'


class OrderCustItemForm(forms.ModelForm):
    class Meta:
        model = OrderCustItem
        fields = '__all__'


class InvoicesForm(forms.ModelForm):
    order = forms.ModelChoiceField(queryset=OrderSup.objects.all(), label='Заказа поставщика',
                                   widget=forms.Select(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = Invoice
        fields = '__all__'


class InvoiceItemForm(forms.Form):
    price = forms.DecimalField(max_digits=10, decimal_places=2)

kursovay1/main/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from .models import OrderCust, OrderCustItem, OrderSup, OrderSupItem, Supplier, SparePart, Invoice, InvoiceItem
from django.urls import reverse
from .forms import OrderCustForm, OrderCustItemForm, InvoiceItemForm, InvoicesForm
from django.db.models import Sum, Q
from datetime import datetime, date
from rest_framework.views import APIView
from rest_framework.response import Response
import io
from django.http import FileResponse
from reportlab.platypus.tables import Table, TableStyle
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib import colors




# Create your views here.


def index(request):
    error = ''
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main/')
        else:
            error = 'Ошибка'
    else:
        form = AuthenticationForm()

    context = {'form': form,
               'error': error,
               'title': 'Авторизация'
               }
    return render(request, 'main/index.html', context)


def main(request):
    user = request.user
    orders = OrderCust.objects.filter(customer=user)
    context = {'title': 'Главная',
               'staff': request.user.is_staff,
               'orders': orders,
               'user': user,
               }
    return render(request, 'main/main.html', context)


def order_cust_type(request, order_id):
    user = request.user
    ordercust = get_object_or_404(OrderCust, pk=order_id)
    if request.method == 'POST':
        type_sale = request.POST['calculation']
        OrderCust.objects.filter(id=ordercust.id).update(type_sale=type_sale)
        return HttpResponseRedirect(reverse('main:main'))

    context = {'title': 'Главная',
               'staff': request.user.is_staff,
               'ordercust': ordercust}
    return render(request, 'main/create_order_type.html', context)


def workspace(request):
    return render(request, 'main/workspace.html', )


def order_sup(request):
    context = {'title': 'Заказы для поставщиков',
               'orders': OrderSup.objects.all(),
               }
    return render(request, 'main/order_sup.html', context)


def form_order_sup(request, order_id):
    order = get_object_or_404(OrderSup, pk=order_id)
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)
    document_title = f'form_order_sup_{order.id}'
    supplier = order.supplier
    title = f'Заказ {supplier}'
    date_ = str(order.date)
    id_ = '0' * (10 - len((str(order.id)))) + str(order.id)
    items = OrderSupItem.objects.filter(order=order)

    p.setTitle(document_title)
    pdfmetrics.registerFont(
        TTFont('abc', 'timesnewromanpsmt.ttf')
    )

    # creating the title by setting it's font
    # and putting it on the canvas
    p.setFont('abc', 16)
    p.drawCentredString(300, 770, title)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.setFont('abc', 14)

    p.drawString(50, 700, 'Код: ' + id_)
    p.drawString(50, 680, 'Дата: ' + date_)

    my_data = [['Название детали', 'Количество'], ]

    for i in items:
        my_data.append([i.spare_part, i.quantity])

    c_width = [3 * inch, 1.5 * inch]
    t = Table(my_data, rowHeights=20, repeatRows=1, colWidths=c_width)
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                           ('FONTSIZE', (0, 0), (-1, -1), 14),
                           ('FONTNAME', (0, 0), (-1, -1), 'abc'),
                           ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                           ('GRID', (0, 0), (-1, -1), 1, colors.black),
                           ]))

    h = 550 - (10 * items.count())
    t.wrapOn(p, 300, 50)
    t.drawOn(p, 50, h)

    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename=f"form_order_sup_{order.id}.pdf")


def create_order_sup(request):
    m = []
    today = date.today()
    gd = datetime(today.year, today.month, today.day, 0, 0, 0)
    ld = datetime(today.year, today.month, today.day + 1, 0, 0, 0)
    order_cust = OrderCust.objects.filter(Q(date__gte=gd) & Q(date__lte=ld))
    for ord in order_cust:
        m.append(ord)
    orders_sup = OrderCustItem.objects.filter(order__in=m).values('supplier').annotate(Sum('quantity'))
    suppliers = Supplier.objects.all()
    for order in orders_sup:
        o = OrderSup.objects.filter(Q(supplier=suppliers.get(id=order['supplier'])) & Q(date__gte=gd) & Q(date__lte=ld))
        if o.count() == 0:
            o = OrderSup(supplier=suppliers.get(id=order['supplier']))
            o.save()
        else:
            o = o.get(supplier=suppliers.get(id=order['supplier']))
        items = OrderCustItem.objects.filter(order__in=m, supplier=suppliers.get(id=order['supplier'])).values('spare_part').annotate(sum_quantity=Sum('quantity'))
        for item in items:
            defaults = {'quantity': item['sum_quantity']}
            obj, created = OrderSupItem.objects.update_or_create(order=o,
                                                  spare_part=SparePart.objects.get(id=item['spare_part']),
                                                  defaults=defaults)
    return HttpResponseRedirect(reverse('main:order_sup'))


def invoices(request):
    error = ''
    if request.method == 'POST':
        form = InvoicesForm(data=request.POST)
        if form.is_valid():
            form.save()
            order_sup = OrderSup.objects.get(id=request.POST['order'])
            items = OrderSupItem.objects.filter(order=order_sup)
            supplier = Supplier.objects.get(id=request.POST['supplier'])
            invoice = Invoice.objects.filter(date=request.POST['date'], supplier=supplier).first()
            for item in items:
                InvoiceItem(invoice=invoice, spare_part=item.spare_part, quantity=item.quantity, price=0, sum_of=0).save()
            return HttpResponseRedirect(reverse('main:invoices'))
        else:
            error = 'Ошибка'
    else:
        form = InvoicesForm()

    context = {'title': 'Накладные',
               'form': form,
               'error': error,
               'orders': Invoice.objects.all()}
    return render(request, 'main/invoices.html', context)


def report(request):
    today = datetime.today()
    sum_to = Invoice.objects.filter(Q(date__gte=datetime(today.year, today.month, 1, 0, 0, 0))
                                          & Q(date__lte=datetime(today.year, today.month + 1,  1, 0, 0, 0))).aggregate(sum_of_=Sum('items__sum_of'))
    sum_pre = Invoice.objects.filter(Q(date__gte=datetime(today.year, today.month - 1, 1, 0, 0, 0))
                                          & Q(date__lte=datetime(today.year, today.month,  1, 0, 0, 0))).aggregate(sum_of_=Sum('items__sum_of'))
    sum_prep = sum_to['sum_of_'] + (sum_to['sum_of_'] - sum_pre['sum_of_'])/2
    context = {'title': 'Отчет',
               'data': Invoice.objects.values('supplier', 'items__spare_part').annotate(sum_of_=Sum('items__sum_of')),
               'sum_prep': sum_prep
               }
    return render(request, 'main/report.html', context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def order_cust(request):
    context = {'title': 'Заказы покупателей',
               'orders': OrderCust.objects.all(),
               }
    return render(request, 'main/order_cust.html', context)


def create_order_cust(request):
    error = ''
    if request.method == 'POST':
        form = OrderCustForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:create_order_cust'))
        else:
            error = 'Ошибка'
    else:
        form = OrderCustForm()
    context = {'title': 'Заказы покупателей',
               'form': form,
               'error': error,
               'orders': OrderCust.objects.all()}
    return render(request, 'main/create_order_cust.html', context)


def create_order_cust_detail(request, order_id):
    order = get_object_or_404(OrderCust, pk=order_id)
    error = ''
    if request.method == 'POST':
        form = OrderCustItemForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:create_order_cust_detail', args=[order.pk, ]))
        else:
            error = 'Ошибка'
    else:
        form = OrderCustItemForm()

    context = {'title': 'Детали заказа',
               'form': form,
               'error': error,
               'order': order,
               'items': OrderCustItem.objects.filter(order=order)}
    return render(request, 'main/create_order_cust_detail.html', context)


def invoice_detail(request, order_id):
    order = get_object_or_404(Invoice, pk=order_id)
    context = {'title': 'Детали накладной',
               'items': InvoiceItem.objects.filter(invoice=order),
               'order': order}
    return render(request, 'main/invoice_detail.html', context)


def add_invoice_detail(request, order_id, item_id):

kursovay1/main/templates/main/add_invoice_detail.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<form action="{% url 'main:add_invoice_detail' order.id item.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Изменить</button>
</form>
{% endblock %}

kursovay1/main/templates/main/create_order_cust.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<form action="{% url 'main:create_order_cust' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Составить</button>
    <a href="{% url 'main:order_cust' %}" class="btn">Выйти</a>
</form>
{% endblock %}

kursovay1/main/templates/main/create_order_type.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<p>
    {{ ordercust.customer_name }}
</p>
<p>
    {{ ordercust.customer_phone }}
</p>
<p>
    {{ ordercust.car }}
</p>
<p>
    {{ ordercust.prepayment }}
</p>
<p>
    {{ ordercust.delivery_time }}
</p>
<form action="{% url 'main:order_cust_type' ordercust.id %}" method="post">
    {% csrf_token %}
    <p>
        <label for="calculation">Способ оплаты:</label>
        <select id="calculation" name="calculation">
            <option value="Наличный Расчёт">Наличный Расчёт</option>
            <option value="Безналичный Расчёт">Безналичный Расчёт</option>
            <option value="Кредит">Кредит</option>
            <option value="Бартер">Бартер</option>
            <option value="Взаимозачёт">Взаимозачёт</option>
        </select>
    </p>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

kursovay1/main/templates/main/index.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<form action="{% url 'main:index' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Авторизоваться</button>
</form>
{% endblock %}

kursovay1/main/templates/main/invoice_detail.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<table id="order_table">
    <thead>
    <tr>
        <th>ID Детали</th>
        <th>Название детали</th>
        <th>Количестов</th>
        <th>Цена</th>
        <th>Сумма</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for item in items %}
    <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.spare_part }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.sum_of }}</td>
        <td>
            <a href="{% url 'main:add_invoice_detail' order.id item.id %}">Указать цену</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<p>
    <a href="{% url 'main:invoices' %}" class="btn">Выйти</a>
</p>
{% endblock %}

kursovay1/main/templates/main/invoices.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<div>
    <table id="order_table">
        <thead>
        <tr>
            <th>ID Накладной</th>
            <th>Дата</th>
            <th>Поставщик</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.date }}</td>
            <td>{{ order.supplier }}</td>
            <td>
                <a href="{% url 'main:invoice_detail' order.id %}">Детали накладной</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<form action="{% url 'main:invoices' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Составить</button>
    <a href="{% url 'main:workspace' %}" class="btn">Выйти</a>
</form>
{% endblock %}

kursovay1/main/templates/main/main.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
{% if staff %}
<a href="{% url 'main:workspace' %}" class="btn">Войти в рабочее место</a>
{% endif %}
<table id="order_table">
    <thead>
    <tr>
        <th>ID Заказа</th>
        <th>Имя клиента</th>
        <th>Сумма предоплаты</th>
        <th>Время прибытия заказа</th>
        <th>Вид продажи</th>
        <th>Детали заказа</th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
    <tr>
        <td>{{ order.id }}</td>
        <td>{{ order.customer_name }}</td>
        <td>{{ order.prepayment }}</td>
        <td>{{ order.delivery_time }}</td>
        <td>{{ order.type_sale }}</td>
        <td>
            <a href="{% url 'main:order_cust_type' order.id %}">Детали заказа</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<p>
    <a href="{% url 'main:logout' %}" class="btn">Выйти</a>
</p>
{{ x }}
{% endblock %}

kursovay1/main/templates/main/order_sup.html
{% extends 'main/base.html'%}

{% block css %}
    .scroll-table-body {
	height: 300px;
	overflow-x: auto;
	margin-top: 0px;
	margin-bottom: 20px;
	border-bottom: 1px solid #eee;
}
.scroll-table table {
	width:100%;
	table-layout: fixed;
	border: none;
}
.scroll-table thead th {
	font-weight: bold;
	text-align: left;
	border: none;
	padding: 10px 15px;
	background: #d8d8d8;
	font-size: 14px;
	border-left: 1px solid #ddd;
	border-right: 1px solid #ddd;
}
.scroll-table tbody td {
	text-align: left;
	border-left: 1px solid #ddd;
	border-right: 1px solid #ddd;
	padding: 10px 15px;
	font-size: 14px;
	vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
	background: #f3f3f3;
}

/* Стили для скролла */
::-webkit-scrollbar {
	width: 6px;
}
::-webkit-scrollbar-track {
	box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
	box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
{% endblock %}

{% block content %}
<p>
    <a href="{% url 'main:create_order_sup' %}" class="btn">Составаить заказы поставщику</a>
</p>
<div class="scroll-table">
    <table id="order_table">
        <thead>
        <tr>
            <th>ID Заказа</th>
            <th>Дата</th>
            <th>Поставщик</th>
            <th></th>
        </tr>
        </thead>
    </table>
    <div class="scroll-table-body">
        <table>
            <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.date }}</td>
                <td>{{ order.supplier }}</td>
                <td>
                    <a href="{% url 'main:form_order_sup' order.id %}">Печать</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<p>
    <a href="{% url 'main:workspace' %}" class="btn">Выйти</a>
</p>
{% endblock %}

kursovay1/main/templates/main/report.html
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>
        table {
            margin-top: 10px;
            margin-right: 5px;
            width: 50%;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border: 1px solid #A9A9A9;
            background-color: #A9A9A9;
        }

        .btn {
            background-color: #A9A9A9;
            color: black;
            padding: 10px 20px;
            border: none;
            text-decoration: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px;
            }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="background-color: #FFFFFF">
<hr />
  <div class="row">
    <div class="col-md-6">
      <canvas id="myBar1"></canvas>
    </div>
    <div class="col-md-6">
      <canvas id="myBar2"></canvas>
    </div>
      <div class="col-md-6">
      <canvas id="myBar3"></canvas>
    </div>
      <div class="col-md-6">
      <canvas id="myBar4"></canvas>
    </div>
  </div>
<div id="parameter_table">
</div>
<p>
    <a class="btn" href="{% url 'main:workspace' %}">Выйти</a>
</p>
<table>
    <thead>
    <tr>
        <th>Поставщик</th>
        <th>Деталь</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
    {% for i in data %}
    <tr>
        {% for v in i.values %}
        <td>{{ v }} </td>
        {% endfor %}
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td>Сумма предоплаты</td>
        <td>{{ sum_prep }}</td>
    </tr>
    </tbody>
</table>
{{ d }}
 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
 <script>
     $.ajax({
        method: "GET",
        url: "{% url 'main:func' %}",
        success: function(data) {
            drawGraph1(data, 'myBar1');
            drawGraph2(data, 'myBar2')
            drawGraph3(data, 'myBar3')
            drawGraph4(data, 'myBar4')
            console.log("drawing");
        },
        error: function(error_data) {
            console.log(error_data);
        }
     })

    function drawGraph1(data, id) {
      var labels = data.labels1;
      var label = data.label1;
      var data = data.data1;
      var ctx = document.getElementById(id).getContext('2d');
      var chart1 = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: labels,
          datasets: [{
            barPercentage: 0.5,
            barThickness: 6,
            maxBarThickness: 8,
            minBarLength: 2,
            backgroundColor: 'rgba(0, 0, 255, 0.2)',
            label: label,
            data: data,
          },]
        },

        // Configuration options go here
        options: {
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });
    }

     function drawGraph2(data, id) {
      var labels = data.labels2;
      var label = data.label2;
      var data = data.data2;
      var ctx = document.getElementById(id).getContext('2d');
      var chart1 = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: labels,
          datasets: [{
            barPercentage: 0.5,
            barThickness: 6,
            maxBarThickness: 8,
            minBarLength: 2,
            backgroundColor: 'rgba(0, 0, 255, 0.2)',
            label: label,
            data: data,
          },]
        },

        // Configuration options go here
        options: {
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });
    }

     function drawGraph3(data, id) {
      var labels = data.labels3;
      var label = data.label3;
      var data = data.data3;
      var ctx = document.getElementById(id).getContext('2d');
      var chart1 = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: labels,
          datasets: [{
            barPercentage: 0.5,
            barThickness: 6,
            maxBarThickness: 8,
            minBarLength: 2,
            backgroundColor: 'rgba(0, 0, 255, 0.2)',
            label: label,
            data: data,
          },]
        },

        // Configuration options go here
        options: {
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });
    }

     function drawGraph4(data, id) {
      var labels = data.labels4;
      var label = data.label4;
      var data = data.data4;
      var ctx = document.getElementById(id).getContext('2d');
      var chart1 = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: labels,
          datasets: [{
            barPercentage: 0.5,
            barThickness: 6,
            maxBarThickness: 8,
            minBarLength: 2,
            backgroundColor: 'rgba(0, 0, 255, 0.2)',
            label: label,
            data: data,
          },]
        },

        // Configuration options go here
        options: {
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });
    }
 </script>
</body>
</html>

kursovay1/main/templates/main/workspace.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<div>
    <a href="{% url 'main:order_sup' %}" class="btn">Составаить заказы поставщику</a>
    <a href="{% url 'main:invoices' %}" class="btn">Составить накладную</a>
    <a href="{% url 'main:report' %}" class="btn">Открыть отчет</a>
    <a href="{% url 'main:order_cust' %}" class="btn">Составить заказы покупателей</a>
    <a href="{% url 'main:main' %}" class="btn">Выйти</a>
</div>
{% endblock %}